[package]
name = "all-crate-grep"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["est31 <MTest31@outlook.com>"]

[[bin]]
name = "all-crate-grep"
path = "main.rs"

[dependencies]

all_crates_storage = { path = "../all_crates_storage" }
grep = "0.1"
